 name: nhgis
 channels:
   - conda-forge
 dependencies:
   - python=3.7
   - geopandas
   - descartes
   - ipython
   - jupyter
   - matplotlib
   - nb_conda_kernels
   - pandas
   - pip
   - shapely
   - watermark
   - pip:
     - git+https://github.com/jGaboardi/nhgisxwalk.git@master
