# This file is part of the Minnesota Population Center's NHGISXWALK.
# For copyright and licensing information, see the NOTICE and LICENSE files
# in this project's top-level directory, and also on-line at:
#   https://github.com/ipums/nhgisxwalk

 name: nhgis
 channels:
   - conda-forge
 dependencies:
   - python=3.8
   - geopandas
   - descartes
   - ipython
   - jupyter
   - matplotlib
   - nb_conda_kernels
   - pandas
   - pip
   - shapely
   - watermark
   - pip:
     - git+https://github.com/ipums/nhgisxwalk.git@master
     - handcalcs
