# This file is part of the Minnesota Population Center's NHGISXWALK.
# For copyright and licensing information, see the NOTICE and LICENSE files
# in this project's top-level directory, and also on-line at:
#   https://github.com/ipums/nhgisxwalk

 name: nhgis
 channels:
   - conda-forge
 dependencies:
   - python=3.11
   - black
   - codecov
   - coverage
   - flake8
   - geopandas
   - handcalcs
   - ipython
   - isort
   - jupyter
   - matplotlib
   - nb_conda_kernels
   - notebook
   - numpy
   - pandas
   - pre-commit
   - pyproject-flake8
   - pytest
   - pytest-cov
   - shapely
   - watermark
   - pip
   - pip:
     - git+https://github.com/ipums/nhgisxwalk.git@main
