# This file is part of the Minnesota Population Center's NHGISXWALK.
# For copyright and licensing information, see the NOTICE and LICENSE files
# in this project's top-level directory, and also on-line at:
#   https://github.com/ipums/nhgisxwalk

 on:
   push:
     branches:
     - '*'
   pull_request:
     branches:
     - '*'
   schedule:
     - cron: '59 23 * * *'

 jobs:
   unittests:
     name: conda (${{ matrix.os }}, ${{ matrix.environment-file }})
     runs-on: ${{ matrix.os }}
     timeout-minutes: 10
     strategy:
       matrix:
         os: ['macos-latest', 'ubuntu-latest', 'windows-latest']
         environment-file: [ci/36.yaml, ci/37.yaml, ci/38.yaml, ci/39.yaml]
     defaults:
       run:
         shell: bash -l {0}
     steps:
       - uses: actions/checkout@v2
       - uses: actions/cache@v2.1.4
         env:
           CACHE_NUMBER: 0
         with:
           path: ~/conda_pkgs_dir
           key: ${{ matrix.os }}-conda-${{ env.CACHE_NUMBER }}-${{ hashFiles(matrix.environment-file) }}
       - uses: conda-incubator/setup-miniconda@v2
         with:
            miniconda-version: 'latest'
            mamba-version: "*"
            channels: conda-forge
            channel-priority: true
            auto-update-conda: false
            auto-activate-base: false
            environment-file: ${{ matrix.environment-file }}
            activate-environment: test
            use-only-tar-bz2: true
       - run: mamba info --all
       - run: mamba list
       - run: pytest -v nhgisxwalk --cov=nhgisxwalk --doctest-modules --cov-config=.coveragerc --cov-report=xml
       - name: codecov (${{ matrix.os }}, ${{ matrix.environment-file }})
         uses: codecov/codecov-action@v1
         with:
           token: ${{ secrets.CODECOV_TOKEN }}
           file: ./coverage.xml
           name: nhgisxwalk-codecov
